### PR TITLE
Replaced topenv with pkg_env

### PR DESCRIPTION
**Pull request by BendettaSD**
Thanks for the implyr package. When trying to wrap the calls into another package for convenience, I got an error message about 'cannot add bindings to a locked environment'.

After reading the options here: [https://groups.google.com/forum/#!topic/rdevtools/tavgQCEomJ8]( https://groups.google.com/forum/#!topic/rdevtools/tavgQCEomJ8) , I decided to change the topenv calls to use the pkg_env you created at the top of the script.

This fixed my packaging issue. Can we apply this change to your repo? Thanks.

### CODE REVIEW

**Comment by BendettaSD** [comment]
Going to look at the failing tests and get back.

**Comment by ianmcook** [comment]
Thanks for discovering and reporting this. implyr uses the unusual approach of defining the `impala_connection` class and its S4 methods in the top-level enclosing environment because this enables implyr to work with multiple DBI-compatible packages (like odbc and RJDBC) instead of just one. This approach is necessary because R's S4 object system doesn't support multiple inheritance with dynamic dispatch. In most cases the top-level environment (`topenv(parent.frame())`) is the global environment, which is unlocked. But in your case it's your package's environment, which is locked.

I believe the fix you applied in this PR will cause failures, because R will never look in the `pkg_env` environment unless it's explicitly told to look there. So it will behave as if the `impala_connection` class and its S4 methods were never defined. Your second commit in this PR caused all the tests to be skipped, which is why they didn't fail. Thanks for noticing those missing calls to `check_impala()`. I need to change the tests so that they *do* fail in this case, but that's a separate issue.)

I think if you change all your instances of `where = pkg_env` to `where = .GlobalEnv` that should solve the problem. Can you make that change and commit it? Thanks!

**Comment by BendettaSD** [comment]
Thanks for the quick reply.

Your explanation makes perfect sense. I will change the 'where's and test the changes.

Adding check_impala() to skip tests was not the right way to pass the build, but I noticed they were missing.

**Comment by ianmcook** [comment]
Merged. Thanks!

**Pull request merged**
